import type { WeeklyRecommendationManifest } from '../lib/weekly-recommendations';

// Generated by scripts/refresh-weekly-recommendations.mjs. Do not edit by hand.
export const WEEKLY_RECOMMENDATIONS_GENERATED_AT = "2026-08-30";

export const WEEKLY_RECOMMENDATIONS: WeeklyRecommendationManifest = {
	"generatedAt": "2026-08-30",
	"weekKey": "2026-08-30",
	"recommendations": [
		{
			"slug": "emilia-perez-2024",
			"era": "nueva"
		},
		{
			"slug": "el-piano-1993",
			"era": "clasica"
		},
		{
			"slug": "mad-max-fury-road-2015",
			"era": "para-descubrir"
		},
		{
			"slug": "one-battle-after-another-2025",
			"era": "nueva"
		},
		{
			"slug": "the-deer-hunter-1978",
			"era": "clasica"
		},
		{
			"slug": "el-renacido-2015",
			"era": "para-descubrir"
		}
	]
};
