import type { WeeklyRecommendationManifest } from '../lib/weekly-recommendations';

// Generated by scripts/refresh-weekly-recommendations.mjs. Do not edit by hand.
export const WEEKLY_RECOMMENDATIONS_GENERATED_AT = "2026-08-30";

export const WEEKLY_RECOMMENDATIONS: WeeklyRecommendationManifest = {
	"generatedAt": "2026-08-30",
	"weekKey": "2026-08-30",
	"recommendations": [
		{
			"slug": "anatomia-de-una-caida-2023",
			"era": "nueva"
		},
		{
			"slug": "the-apartment-1960",
			"era": "clasica"
		},
		{
			"slug": "the-housemaid-2025",
			"era": "nueva"
		},
		{
			"slug": "no-country-for-old-men-2007",
			"era": "clasica"
		},
		{
			"slug": "platoon-1986",
			"era": "clasica"
		},
		{
			"slug": "los-angeles-al-desnudo-1997",
			"era": "clasica"
		}
	]
};
