import type { WeeklyRecommendationManifest } from '../lib/weekly-recommendations';

// Snapshot generated by scripts/refresh-weekly-recommendations.mjs. Do not edit by hand.
// The homepage computes the current edition at build time from the catalog.
export const WEEKLY_RECOMMENDATIONS_GENERATED_AT = "2026-09-20";

export const WEEKLY_RECOMMENDATIONS: WeeklyRecommendationManifest = {
	"generatedAt": "2026-09-20",
	"weekKey": "2026-09-20",
	"recommendations": [
		{
			"slug": "love-lies-bleeding-2024",
			"era": "nueva"
		},
		{
			"slug": "invencible-2006",
			"era": "clasica"
		},
		{
			"slug": "the-breadwinner-el-pan-de-la-guerra-2017",
			"era": "para-descubrir"
		},
		{
			"slug": "septiembre-5-2024",
			"era": "nueva"
		},
		{
			"slug": "el-graduado-1967",
			"era": "clasica"
		},
		{
			"slug": "kung-fu-panda-3-2016",
			"era": "para-descubrir"
		}
	]
};
